#ifndef GUARD_CONFIG_GAME_SETTINGS_H
#define GUARD_CONFIG_GAME_SETTINGS_H

#define GAME_SETTING_DIFFICULTY_NORMAL_MODE                   0
#define GAME_SETTING_DIFFICULTY_EASY_MODE                     1

#endif // GUARD_CONFIG_GAME_SETTINGS_H
