#ifndef GUARD_CONSTANTS_HEXORB_H
#define GUARD_CONSTANTS_HEXORB_H

enum {
    HEXORB_RESULT_FAINTED_OR_NO_MON,
    HEXORB_RESULT_ABILITY,
    HEXORB_RESULT_TYPE_0,
    HEXORB_RESULT_TYPE_1,
    HEXORB_RESULT_SUCCESS,
    HEXORB_RESULT_COUNT,
};

#endif // GUARD_CONSTANTS_HEXORB_H
