#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_MATT_SEAFLOOR_CAVERN          7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_MATT_WEATHER_INST            18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GARDENIA2                    23
#define TRAINER_DOLLAMIKE                    24
#define TRAINER_DANNI                        25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_ARCHIE_HIDEOUT               30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_DUSTY_1                      44
#define TRAINER_MASTA_JANES                  45
#define TRAINER_FOSTER                       46
#define TRAINER_DUSTY_2                      47
#define TRAINER_UNUSED_221                   48
#define TRAINER_SIDNEY_DOUBLE_HC1            49
#define TRAINER_SIDNEY_DOUBLE_HC2            50
#define TRAINER_GABBY_AND_TY_1               51
#define TRAINER_GABBY_AND_TY_2               52
#define TRAINER_GABBY_AND_TY_3               53
#define TRAINER_GABBY_AND_TY_4               54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56
#define TRAINER_LOLA_1                       57
#define TRAINER_AUSTINA                      58
#define TRAINER_GWEN                         59
#define TRAINER_LOLA_2                       60
#define TRAINER_UNUSED_9                     61
#define TRAINER_UNUSED_10                    62
#define TRAINER_UNUSED_11                    63
#define TRAINER_RICKY_1                      64
#define TRAINER_BRIAN                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_RICKY_2                      67
#define TRAINER_UNUSED_12                    68
#define TRAINER_UNUSED_13                    69
#define TRAINER_UNUSED_14                    70
#define TRAINER_MASTER_POUCINE               71
#define TRAINER_OBLIVION_WING                72
#define TRAINER_BRIAN_2                      73
#define TRAINER_BURAK                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON_1                     78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMUEL                       81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WILTON_2                     84
#define TRAINER_UNUSED_15                    85
#define TRAINER_UNUSED_16                    86
#define TRAINER_UNUSED_17                    87
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89 //unused norman gym
#define TRAINER_ALEXIA                       90 //unused norman gym
#define TRAINER_JODY                         91 //unused norman gym
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_UNUSED_18                   102
#define TRAINER_UNUSED_19                   103
#define TRAINER_UNUSED_20                   104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_UNUSED_21                   111
#define TRAINER_UNUSED_22                   112
#define TRAINER_UNUSED_23                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_UNUSED_24                   120
#define TRAINER_UNUSED_25                   121
#define TRAINER_UNUSED_26                   122
#define TRAINER_UNUSED_27                   123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_UNUSED_28                   133
#define TRAINER_UNUSED_29                   134
#define TRAINER_UNUSED_30                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_UNUSED_31                   140
#define TRAINER_UNUSED_32                   141
#define TRAINER_UNUSED_33                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_COURTNEY_MT_CHIMNEY         146
#define TRAINER_STEVE_2                     147
#define TRAINER_UNUSED_34                   148
#define TRAINER_UNUSED_35                   149
#define TRAINER_UNUSED_36                   150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_UNUSED_37                   176
#define TRAINER_UNUSED_38                   177
#define TRAINER_UNUSED_39                   178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_UNUSED_40                   185
#define TRAINER_UNUSED_41                   186
#define TRAINER_UNUSED_42                   187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_UNUSED_43                   198
#define TRAINER_UNUSED_44                   199
#define TRAINER_UNUSED_45                   200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_UNUSED_46                   208
#define TRAINER_UNUSED_47                   209
#define TRAINER_UNUSED_48                   210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_RUSTY                       215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_UNUSED_49                   220
#define TRAINER_UNUSED_50                   221
#define TRAINER_UNUSED_51                   222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_IRIV24                      227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_UNUSED_52                   229
#define TRAINER_UNUSED_53                   230
#define TRAINER_UNUSED_54                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_UNUSED_55                   240
#define TRAINER_UNUSED_56                   241
#define TRAINER_UNUSED_57                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_UNUSED_58                   251
#define TRAINER_UNUSED_59                   252
#define TRAINER_UNUSED_60                   253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_UNUSED_61                   258
#define TRAINER_UNUSED_62                   259
#define TRAINER_UNUSED_63                   260
#define TRAINER_SIDNEY1                     261
#define TRAINER_PHOEBE1                     262
#define TRAINER_GLACIA1                     263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_JERRY_1                     273
#define TRAINER_TED                         274
#define TRAINER_RACHEL                      275
#define TRAINER_JERRY_2                     276
#define TRAINER_UNUSED_64                   277
#define TRAINER_UNUSED_65                   278
#define TRAINER_UNUSED_66                   279
#define TRAINER_KAREN_1                     280
#define TRAINER_GEORGIA                     281
#define TRAINER_KAREN_2                     282
#define TRAINER_UNUSED_67                   283
#define TRAINER_UNUSED_68                   284
#define TRAINER_UNUSED_69                   285
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG_1              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_UNUSED_70                   289
#define TRAINER_UNUSED_71                   290
#define TRAINER_UNUSED_72                   291
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL_1                    293
#define TRAINER_COLTON                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_UNUSED_73                   296
#define TRAINER_UNUSED_74                   297
#define TRAINER_UNUSED_75                   298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_UNUSED_76                   304
#define TRAINER_UNUSED_77                   305
#define TRAINER_UNUSED_78                   306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_UNUSED_79                   309
#define TRAINER_UNUSED_80                   310
#define TRAINER_UNUSED_81                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_UNUSED_82                   315
#define TRAINER_UNUSED_83                   316
#define TRAINER_UNUSED_84                   317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_UNUSED_85                   329
#define TRAINER_UNUSED_86                   330
#define TRAINER_UNUSED_87                   331
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_WALLACE                     335
#define TRAINER_FANTINA                     336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_UNUSED_88                   347
#define TRAINER_UNUSED_89                   348
#define TRAINER_UNUSED_90                   349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_UNUSED_91                   355
#define TRAINER_UNUSED_92                   356
#define TRAINER_UNUSED_93                   357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_UNUSED_94                   361
#define TRAINER_UNUSED_95                   362
#define TRAINER_UNUSED_96                   363
#define TRAINER_DYLAN_1                     364
#define TRAINER_DYLAN_2                     365
#define TRAINER_UNUSED_97                   366
#define TRAINER_UNUSED_98                   367
#define TRAINER_UNUSED_99                   368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_UNUSED_100                  371
#define TRAINER_UNUSED_101                  372
#define TRAINER_UNUSED_102                  373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_UNUSED_103                  380
#define TRAINER_UNUSED_104                  381
#define TRAINER_UNUSED_105                  382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_UNUSED_106                  389
#define TRAINER_UNUSED_107                  390
#define TRAINER_UNUSED_108                  391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_UNUSED_109                  394
#define TRAINER_UNUSED_110                  395
#define TRAINER_UNUSED_111                  396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_UNUSED_112                  410
#define TRAINER_UNUSED_113                  411
#define TRAINER_UNUSED_114                  412
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO_1                       419
#define TRAINER_LUNG                        420
#define TRAINER_LAO_2                       421
#define TRAINER_UNUSED_115                  422
#define TRAINER_UNUSED_116                  423
#define TRAINER_UNUSED_117                  424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY_1                     427
#define TRAINER_CORA                        428
#define TRAINER_PAULA                       429
#define TRAINER_CYNDY_2                     430
#define TRAINER_UNUSED_118                  431
#define TRAINER_UNUSED_119                  432
#define TRAINER_UNUSED_120                  433
#define TRAINER_MADELINE_1                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_UNUSED_121                  438
#define TRAINER_UNUSED_122                  439
#define TRAINER_UNUSED_123                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_UNUSED_124                  466
#define TRAINER_UNUSED_125                  467
#define TRAINER_UNUSED_126                  468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_UNUSED_127                  478
#define TRAINER_UNUSED_128                  479
#define TRAINER_UNUSED_129                  480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_UNUSED_130                  485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_UNUSED_131                  487
#define TRAINER_UNUSED_132                  488
#define TRAINER_UNUSED_133                  489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_UNUSED_134                  498
#define TRAINER_UNUSED_135                  499
#define TRAINER_UNUSED_136                  500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_UNUSED_137                  516
#define TRAINER_UNUSED_138                  517
#define TRAINER_UNUSED_139                  518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_EZEKIEL_1                   538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_EZEKIEL_2                   541
#define TRAINER_UNUSED_140                  542
#define TRAINER_UNUSED_141                  543
#define TRAINER_UNUSED_142                  544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_UNUSED_143                  549
#define TRAINER_UNUSED_144                  550
#define TRAINER_UNUSED_145                  551
#define TRAINER_JACKSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_JACKSON_2                   555
#define TRAINER_UNUSED_146                  556
#define TRAINER_UNUSED_147                  557
#define TRAINER_UNUSED_148                  558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_UNUSED_149                  563
#define TRAINER_UNUSED_150                  564
#define TRAINER_UNUSED_151                  565
#define TRAINER_MAYLENE                     566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_TATE                        568
#define TRAINER_LIZA                        569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_SIDNEY2                     586
#define TRAINER_PHOEBE2                     587
#define TRAINER_GLACIA2                     588
#define TRAINER_WALLACE_WITH_STEVEN         589
#define TRAINER_STEVEN_WITH_WALLACE         590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_UNUSED_152                  608
#define TRAINER_UNUSED_153                  609
#define TRAINER_UNUSED_154                  610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_UNUSED_155                  623
#define TRAINER_UNUSED_156                  624
#define TRAINER_UNUSED_157                  625
#define TRAINER_WAKE                        626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_UNUSED_158                  637
#define TRAINER_UNUSED_159                  638
#define TRAINER_UNUSED_160                  639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_UNUSED_161                  644
#define TRAINER_UNUSED_162                  645
#define TRAINER_UNUSED_163                  646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_ROUTE_110             658
#define TRAINER_BEFOOLS                     659
#define TRAINER_NATN                        660
#define TRAINER_BRENDAN_EVERGRANDE_MUDKIP   661
#define TRAINER_BRENDAN_EVERGRANDE_TREECKO  662
#define TRAINER_BRENDAN_EVERGRANDE_TORCHIC  663
#define TRAINER_MAY_EVERGRANDE_MUDKIP       664
#define TRAINER_MAY_EVERGRANDE_TREECKO      665
#define TRAINER_MAY_EVERGRANDE_TORCHIC      666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_UNUSED_164                  683
#define TRAINER_UNUSED_165                  684
#define TRAINER_UNUSED_166                  685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_UNUSED_167                  689
#define TRAINER_UNUSED_168                  690
#define TRAINER_UNUSED_169                  691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_ROARK                       710
#define TRAINER_BYRON                       711
#define TRAINER_VOLKNER                     712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_SUNBIRD                     726
#define TRAINER_SUNEAL                      727
#define TRAINER_COURTNEY                    728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_DAWN_ROUTE_111              744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_X                           755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RAQUEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_UNUSED_170                  771
#define TRAINER_UNUSED_171                  772
#define TRAINER_UNUSED_172                  773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_UNUSED_173                  775
#define TRAINER_UNUSED_174                  776
#define TRAINER_UNUSED_175                  777
#define TRAINER_WATTSON_2                   778
#define TRAINER_UNUSED_176                  779
#define TRAINER_UNUSED_177                  780
#define TRAINER_UNUSED_178                  781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_UNUSED_179                  783
#define TRAINER_UNUSED_180                  784
#define TRAINER_UNUSED_181                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_UNUSED_182                  787
#define TRAINER_UNUSED_183                  788
#define TRAINER_UNUSED_184                  789
#define TRAINER_WINONA_2                    790
#define TRAINER_UNUSED_185                  791
#define TRAINER_UNUSED_186                  792
#define TRAINER_UNUSED_187                  793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_UNUSED_188                  795
#define TRAINER_UNUSED_189                  796
#define TRAINER_UNUSED_190                  797
#define TRAINER_JUAN_2                      798
#define TRAINER_UNUSED_191                  799
#define TRAINER_UNUSED_192                  800
#define TRAINER_UNUSED_193                  801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804  // unused
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_BURMYKID                    813
#define TRAINER_UNUSED_4                    814
#define TRAINER_UNUSED_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_UNUSED_197                  817
#define TRAINER_UNUSED_198                  818
#define TRAINER_UNUSED_199                  819
#define TRAINER_PABLO_2                     820
#define TRAINER_UNUSED_200                  821
#define TRAINER_UNUSED_201                  822
#define TRAINER_UNUSED_202                  823
#define TRAINER_KOJI_2                      824
#define TRAINER_UNUSED_203                  825
#define TRAINER_UNUSED_204                  826
#define TRAINER_UNUSED_205                  827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_UNUSED_206                  829
#define TRAINER_UNUSED_207                  830
#define TRAINER_UNUSED_208                  831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_UNUSED_209                  833
#define TRAINER_UNUSED_210                  834
#define TRAINER_UNUSED_211                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_UNUSED_212                  837
#define TRAINER_UNUSED_213                  838
#define TRAINER_UNUSED_214                  839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_UNUSED_215                  841
#define TRAINER_UNUSED_216                  842
#define TRAINER_UNUSED_217                  843
#define TRAINER_THALIA_2                    844
#define TRAINER_UNUSED_218                  845
#define TRAINER_UNUSED_219                  846
#define TRAINER_UNUSED_220                  847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_CANDICE                     851
#define TRAINER_GARDENIA                    852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854
#define TRAINER_DAWN_ROUTE_104              855
#define TRAINER_URSULA                      856
#define TRAINER_CAP                         857
#define TRAINER_DAWN_LILYCOVE               858
#define TRAINER_DAWN_EVERGRANDE             859
#define TRAINER_CYNTHIA                     860

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      861
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H