name: 🧠 Battle AI bugs 🐛
description: File a bug report related to battle AI. This could be anything from not playing optimally (which I recognize is subjective) to the AI getting stuck in a loop of some sort.
labels: ["bug", "status: unconfirmed", "category: battle-ai"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all required fields with as many details as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Emerald Imperium are you playing?
      options:
        - 1.0
        - beta
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so we can contact you in case we need more details. Be sure to join the Discord server ([here](https://discord.gg/XJkctHqR)).
      placeholder: ex. iriv24#8479
    validations:
      required: false
